apiVersion: v1
kind: Service
metadata:
  name: recommendation-api-service
  labels:
    app: recommendation-engine
spec:
  selector:
    app: recommendation-engine
    tier: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-frontend-service
  labels:
    app: recommendation-engine
spec:
  selector:
    app: recommendation-engine
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
